volumes:
  db:

networks:
  intranet:
    driver: bridge

services:
  api:
    build: .
    ports:
      - 4000:3000
    networks:
      - intranet
  database:
    image: surrealdb/surrealdb:latest
    user: root
    ports:
      - 4001:8000
    networks:
      - intranet
    volumes:
      - db:/database
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - file:/database/database.db
